name: CI/CD

on:
  push:
    branches: ["main"]
    paths:    
      - 'app/**'
      - 'iac/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REPO: tv-devops-repo
      STACK_NAME: tv-devops

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Install IaC deps
        working-directory: iac
        run: npm ci

      - name: Generate CDKTF provider bindings
        working-directory: iac
        run: npx -y cdktf-cli@latest get

      - name: Deploy with CDKTF (bootstrap infra + ECR)
        working-directory: iac
        env:
          IMAGE_TAG: ${{ github.sha }} 
          STACK_NAME: tv-devops
          ECR_REPO: tv-devops-repo
          AWS_REGION: us-east-1
          AWS_DEFAULT_REGION: us-east-1
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          TF_LOCK_TABLE: tv-devops-terraform-locks
          TF_STATE_KEY: tv-devops/terraform.tfstate
        run: |
          npx -y cdktf-cli@latest deploy $STACK_NAME --auto-approve

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: tv-devops-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG ./app
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
            
      - name: Deploy with CDKTF (update ECS to new image)
        working-directory: iac
        env:
          IMAGE_TAG: ${{ github.sha }}
          STACK_NAME: tv-devops
          AWS_REGION: us-east-1
          AWS_DEFAULT_REGION: us-east-1
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          TF_LOCK_TABLE: tv-devops-terraform-locks
          TF_STATE_KEY: tv-devops/terraform.tfstate
        run: |
          npx -y cdktf-cli@latest deploy $STACK_NAME --auto-approve
